apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: book-import-app.yaml
    namespace: openshift-gitops
  spec:
    destination:
      namespace: dev-project1
      server: https://kubernetes.default.svc
    project: dev-project1
    source:
      path: overlay/dev
      repoURL: https://github.com/damianlezcano/book-import.git
      targetRevision: main
    syncPolicy: {}
#    syncPolicy:
#      automated:
#        selfHeal: false
#      syncOptions:
#      - Validate=false
#      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
