apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: dev-example-app
    namespace: openshift-gitops
  spec:
    destination:
      namespace: dev-project1
      server: https://kubernetes.default.svc
    project: dev-project1
    source:
      path: overlay/dev
      repoURL: https://github.com/damianlezcano/book-import.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - Validate=false
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
