apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: openshift-gitops
spec:
  destination:
    namespace: 'openshift-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    path: ocp01/proyectos
    repoURL: https://github.com/damianlezcano/openshift-gitops.git
    targetRevision: https
  project: openshift-gitops
  syncPolicy: {}
#  syncPolicy:
#    automated:
#      selfHeal: true
#    syncOptions:
#      - Validate=false
#      - CreateNamespace=true
#      - ApplyOutOfSyncOnly=true
